First review Html and Css
Feliverse/reviewIvanProject pull request #3
Opened 2022-12-05 16:36 UTC by Feliverse

2022-12-05 17:18 UTC, bienvenuushindi requested changes
# Changes Required ♻️
### Hi :wave: @Feliverse   ,

Nice job :clap: :100: , you are almost there.

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## (Highlights) Good Points: :+1:

- :heavy_check_mark: Descriptive PR title.

## Required Changes :recycle: 

 - [ ] Your review should have at least two comments. So far there is no comment. Please add at least two comments as requested in the [project requirements ](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/review_your_project.md#project-requirements)
 > ![requirement](https://user-images.githubusercontent.com/26736582/196961862-17f1abdf-0c8d-4c06-b922-c780e7644a39.png)

- [x] Kindly check comments under the review.

## [Optional] suggestions:

- [x] I think it will be great if you use a couple of emojis and/or gifs in the review. They make the code review more human-friendly 👽🤖.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-12-05 19:19 UTC, Alfredbis29 reviewed
Hi @Feliverse , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have any review comment or any request changes , kindly make some review to this PR then when you will be ready you can request re-review , I invalid this project because the requirements said that you should do atleast 2 review comments for this project . :wink:  and there is nothing I will review in this PR 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-05 19:46 UTC, RiyaBulia12 reviewed
Hi @Feliverse , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] You have submitted a project without reviewing it. Kindly review the project as per your knowledge by adding comments giving suggestions/feedback/enhancements for the project which you think can help improve the projects 👍🏽 💯 🔢 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-05 20:45 UTC, iambenkis requested changes
Hi @Feliverse , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 

- [ ] You have submitted a project without reviewing it. Thanks means you did not work on this exercise. :3rd_place_medal: 
- [ ] [**REMINDER**] This exercise is about performing code review :recycle:  on your code. Kindly may sure you read the [project's requirements](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/review_your_project.md).  :+1: 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-05 23:47 UTC, Feliverse commented
### Hi code reviewers,
**I have an explanation: In the first review I did only one Comment, which was:**

![Capture screen 2022-12-05 193623](https://user-images.githubusercontent.com/114632980/205768051-391f6206-0374-4dd3-abc4-f1ae689b853c.png)

**Then, I follow the Changes required:**
![image](https://user-images.githubusercontent.com/114632980/205768470-24d06f17-b2e7-460b-9ab0-5a16c01a4bdd.png)

**The result is this _second Comment:_**
![image](https://user-images.githubusercontent.com/114632980/205769152-23bceef4-4e50-4ac9-829e-d0ef561d9698.png)


**Please consider it, I think that I complete the Requirements**

2022-12-06 00:04 UTC, huseyinbiyik commented
Hi @Feliverse,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![Alt Text](https://media.giphy.com/media/xUPGcwE3CUkXlvonug/giphy.gif)

## Invalid Code Review Request

- Kindly add at least 2 review comments for this project. 🥈

<img width="693" alt="Screenshot 2022-12-06 at 2 58 20 AM" src="https://user-images.githubusercontent.com/25887253/205772257-4d2be95f-e191-4624-9f81-dd7f4a760998.png">

The problem is your comments are "pending" state so you are the only one seeing your comments. 👍

- Kindly check the workflow below for adding inline comments.
![Screen Recording 2022-12-06 at 2 56 48 AM](https://user-images.githubusercontent.com/25887253/205772539-55952b29-9ef6-47cb-b561-62fbc84f1293.gif)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-06 00:14 UTC, Feliverse reviewed
I´m following your sugestion 👍
Thank you  😎

2022-12-06 00:14 UTC, Feliverse commented on index.html
Hi Felipe,
Nice work whit your formulary, Is important to use Html semantics in a good way, se the appropriate tags for each element (e.g., links, titles, etc.) and use HTML5 semantic tags (e.g., header, nav) over divs.
See it for help:  https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md

2022-12-06 00:14 UTC, Feliverse commented on index.html
>            <select name="dropdown" id="dropdown" class="textbox">
Felipe, the formulary is functional, 👌 but you would write _less code_ if you use `<ul>` and `<li>`.
See this video👀 : https://youtu.be/okbByPWS1Xc
try it in your next form 😜

2022-12-06 00:16 UTC, Feliverse commented
@huseyinbiyik 
Thank you so much

2022-12-06 00:23 UTC, Tadesse-Alemayehu approved these changes
### Hi @Feliverse 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![68747470733a2f2f6669636f666f72756d732e6d796669636f2e636f6d2f74352f696d6167652f736572766572706167652f696d6167652d69642f343932363069463839303835363833444139334135422f696d6167652d73697](https://user-images.githubusercontent.com/69077061/200411711-6e741427-6e46-4354-932f-f1445ecc09bd.gif)

## Highlights
- [ ] phrased the comments politely ✔
- [ ]  includes an explanation, a "why", for each requested change. ✔
- [ ]  comments are clear and easy to understand. ✔

## Optional suggestions
- [Optional] Dear @Feliverse , Good job, One major thing you can do to make your review human-friendly is to use emojis in your summary. (Like the one I'm using right now).

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-12-15 02:06 UTC, merged